use proyectodb;
#INSERTAR DATOS A AUTOR, LIBRO, USUARIO, ALMACEN

#MOSTRAR NOMBRE, APELLIDO PATERNO Y MATERNO, ID, CORREO DE AUTOR

#MOSTRAR NOMBRE, APELLIDO PATERNO Y MATERNO, ID, CORREO DE USUARIO

#MOSTRAR TODOS LOS DATOS DE ALMACEN

#MOSTRAR TODOS LOS DATOS DE LIBRO